-- Insertando algunos registros para que la base de datos no este vacia

INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10308,2,'1996-09-18');
INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10309,37,'1996-09-19');
INSERT INTO ORDERS (ID,CUSTOMER_ID,ORDER_DATE) VALUES (10310,77,'1996-09-20');

INSERT INTO USERS (USERNAME,EMAIL,PASSWORD) VALUES ('user1','user1@example.com','{noop}querty123');
INSERT INTO USERS (USERNAME,EMAIL,PASSWORD) VALUES ('user2','user2@example.com','{noop}querty456');

INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (1, 'BTCUSDT', 1.12);
INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (1, 'ETHUSDT', 3.5);
INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (1, 'LTCUSDT', 4);

INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (2, 'BTCUSDT', 0.32);
INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (2, 'ETHUSDT', 1.78);
INSERT INTO ACCOUNTS (USER_ID, SYMBOL, AMOUNT) VALUES (2, 'LTCUSDT', 3.2);



