-- Examples

DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ACCOUNTS;

CREATE TABLE ORDERS (
    ORDER_ID INTEGER IDENTITY PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    ORDER_DATE DATE NOT NULL,
    SYMBOL VARCHAR(35),
    AMOUNT FLOAT,
    BUY INTEGER,
    PRICE FLOAT
);


CREATE TABLE "USERS" (
    "USER_ID" IDENTITY(1,1) NOT NULL PRIMARY KEY,
    "USERNAME" VARCHAR(40) NOT NULL,
    "EMAIL" VARCHAR(35) NOT NULL,
    "PASSWORD" VARCHAR(512) NOT NULL
);

CREATE TABLE "ACCOUNTS" (
    "ACCOUNT_ID" IDENTITY(1,1) NOT NULL PRIMARY KEY,
    "USER_ID" INTEGER NOT NULL,
    "SYMBOL" VARCHAR(35),
    "AMOUNT" FLOAT
)